apiVersion: v1
kind: Deployment
metadata:
  name: tomcat-deployment
  labels:
    app: tomcat
spec:
  replicas: 3
  selector:
    matchLabels:
      app: tomcat
  template:
    metadate:
      labels:
         app: tomcat
    spec:
      containers:
      - name: tomcat-deployment
        image: tomcat:latest
        ports:
        - containerport: 8080