apiVersion: v1

kind: Deployment
metadata:
  name: tomcat-deployment
  labels:
    app: tomcat
spec:
  replicas: 3
  selector:
    matchLabels:
      app: tomcat
  template:
    metadate:
      labels:
         app: tomcat
    spec:
      containers:
      - name: tomcat-deployment
        image: tomcat:latest
        env:
          - name: MONGO_INITDB_ROOT_USERNAME
              volueForm:
                ConfigMapRefKey:
                   key: username
                   name: configmaps


         - name: MONGO_INITDB_ROOT_PASSWD
             volumeForm:
               secretRefKey:
                 key: password
                 name: secret
                 